model_name_or_path: /hy-tmp/models/Qwen/Qwen3-4B-Instruct-2507
template: qwen3_nothink
infer_backend: huggingface
trust_remote_code: true
cache_dir: /hy-tmp/models
do_sample: false
max_new_tokens: 512
